version: "3.9"

services:
  backend:
    build: ./backend
    container_name: face-med-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: face-med-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
